'use client';
import {useEffect,useRef,useState} from 'react';
import {LoaderCircle,CheckCircle2,AlertCircle,X,Trash2} from 'lucide-react';
import {emptyApplications,emptyContact,validApplicationURL,applicationJobKey,type Application,type ApplicationWorkspace,type Contact} from '../lib/applications';

type SearchJob={title:string;company:string;url:string;source:string;description:string;location:string;warning?:string};
type CompanionApplicationReply=Partial<Application>&{error?:string;version?:string;restartRequired?:boolean;text:string;base64:string;models:string[];defaultModel:string;message:string;filled:string[];skipped:string[];jobs:SearchJob[];keywords:string;location:string};
export default function Applications({bridge,token,profile,onBusyChange}:{bridge:string;token:string;profile:string;onBusyChange?:(busy:boolean)=>void}){
 const [data,setData]=useState<ApplicationWorkspace>(emptyApplications),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('jobs'),[selected,setSelected]=useState(''),[models,setModels]=useState<string[]>([]),[url,setUrl]=useState(''),[filter,setFilter]=useState('all'),[confirmed,setConfirmed]=useState(false),[submitted,setSubmitted]=useState(false);
 const [stage,setStage]=useState(''),[elapsed,setElapsed]=useState(0),[retry,setRetry]=useState<(()=>Promise<void>)|null>(null);
 const [searchCriteria,setSearchCriteria]=useState({keywords:'',location:'',workMode:'any',days:'7',limit:5}),[foundJobs,setFoundJobs]=useState<SearchJob[]>([]),[searchSummary,setSearchSummary]=useState('');
 const working=useRef(false);
 useEffect(()=>{if(!busy)return;const start=Date.now();setElapsed(0);const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer)},[busy]);
 const ref=useRef(data);ref.current=data;
 const saveQueue=useRef(Promise.resolve());
 const message=(e:unknown)=>e instanceof Error?e.message:'Operation failed. Please retry.';
 async function load(){try{const r=await fetch('/api/applications');const d=await r.json() as ApplicationWorkspace&{error?:string};if(!r.ok)throw Error(d.error);const next={...emptyApplications,...d,provider:d.provider||(d.model?'ollama':'groq'),contact:{...emptyContact,...d.contact},profile:d.profile||profile,model:d.model||(d.provider==='ollama'?'':'openai/gpt-oss-20b')};ref.current=next;setData(next);setReady(true);setError('')}catch(e){setError(message(e))}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{setConfirmed(false);setSubmitted(false)},[selected]);
 async function save(next=ref.current){if(working.current)setStage("Saving your changes");ref.current=next;setData(next);setDirty(true);const task=saveQueue.current.catch(()=>{}).then(async()=>{const r=await fetch('/api/applications',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const result=await r.json() as CompanionApplicationReply;if(!r.ok)throw Error(result.error)});saveQueue.current=task;await task;if(saveQueue.current===task)setDirty(false)}
 async function run(label:string,work:()=>Promise<void>){if(working.current)return;working.current=true;onBusyChange?.(true);setBusy(label);setStage('Starting');setElapsed(0);setRetry(null);setError('');setNotice('');try{await work();setNotice(current=>current||label+' completed.')}catch(e){setError(message(e));setRetry(()=>()=>run(label,work))}finally{working.current=false;onBusyChange?.(false);setBusy('')}}
 async function api(route:string,payload?:unknown){setStage(({'/health':'Checking companion connection','/ollama-status':'Connecting to Ollama','/cv-import':'Extracting text from your CV','/job-search-plan':'Finding search suggestions in your profile','/job-search':'Searching LinkedIn and reading job descriptions','/job-import':'Opening the job and reading its description','/application-provider-status':'Checking your AI provider','/application-draft':(ref.current.provider==='groq'?'Groq':'Ollama')+' is scoring the match and writing your documents','/application-document':'Creating your document download','/application-prepare':'Opening the application and filling supported fields'} as Record<string,string>)[route]||'Working');if(!token.trim())throw Error('Connect the companion in Settings first.');const r=await fetch(bridge+route,{method:payload?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined,signal:AbortSignal.timeout(620000)}).catch(()=>{throw Error('The companion did not respond. Start npm start, reconnect in Settings, and retry.')});const result=await r.json() as CompanionApplicationReply;if(!r.ok)throw Error(result.error||'Companion request failed');return result}
 async function check(){const health=await api('/health');if(health.version!=='2.4.0'||health.restartRequired)throw Error('Restart the updated companion and reconnect in Settings to use Applications.')}
 function update(values:Partial<ApplicationWorkspace>){setRetry(null);const next={...ref.current,...values,jobs:ref.current.jobs.map(j=>j.status==='approved'?{...j,status:'review' as const,approvedAt:''}:j)};ref.current=next;setData(next);setDirty(true);setConfirmed(false)}
 function edit(id:string,patch:Partial<Application>){setRetry(null);const next={...ref.current,jobs:ref.current.jobs.map(j=>j.id===id?{...j,...patch,status:j.resume?'review' as const:'saved' as const,approvedAt:''}:j)};ref.current=next;setData(next);setDirty(true);setConfirmed(false)}
 async function patch(id:string,values:Partial<Application>){await save({...ref.current,jobs:ref.current.jobs.map(j=>j.id===id?{...j,...values}:j)})}
 async function remove(job:Application){
  if(working.current||!window.confirm('Remove "'+job.title+'" and its saved documents from your workspace?'))return;
  await run('Removing job',async()=>{
   const before=ref.current,wasDirty=dirty;
   try{await save({...before,jobs:before.jobs.filter(j=>j.id!==job.id)})}catch(e){ref.current=before;setData(before);setDirty(wasDirty);throw e}
   setSelected('');setConfirmed(false);setSubmitted(false);setNotice('Job and its saved documents removed.');
  });
 }
 function newJob(imported:Partial<Application>):Application{return {id:crypto.randomUUID(),title:'Untitled role',company:'',source:'Manual',url:'',description:'',status:'saved',score:null,summary:'',matches:[],gaps:[],resume:'',coverLetter:'',evidence:[],model:'',generatedAt:'',approvedAt:'',appliedAt:'',...imported}}
 async function add(imported:Partial<Application>){const job=newJob(imported);if(job.url&&ref.current.jobs.some(j=>applicationJobKey(j.url)===applicationJobKey(job.url))){setSelected(ref.current.jobs.find(j=>j.url===job.url)!.id);setNotice('This job is already saved.');return}await save({...ref.current,jobs:[job,...ref.current.jobs]});setSelected(job.id);setTab('jobs');setUrl('')}
 async function saveFound(candidates:SearchJob[]){await run('Saving jobs',async()=>{const before=ref.current,wasDirty=dirty,seen=new Set(before.jobs.map(job=>applicationJobKey(job.url)));const added=candidates.filter(job=>{const key=applicationJobKey(job.url);if(seen.has(key))return false;seen.add(key);return true}).map(job=>newJob({title:job.title,company:job.company,url:job.url,description:job.description,source:job.source}));if(!added.length){setNotice('These jobs are already saved.');return}if(before.jobs.length+added.length>100)throw Error('Your workspace holds up to 100 jobs. Remove some jobs before saving more.');try{await save({...before,jobs:[...added,...before.jobs]})}catch(e){ref.current=before;setData(before);setDirty(wasDirty);throw e}setSelected(added[0].id);setFilter('all');setNotice(added.length+' job'+(added.length===1?'':'s')+' saved to Applications.')})}
 async function upload(file:File){await run('Reading CV',async()=>{if(file.size>5*1024*1024)throw Error('Use a PDF or DOCX under 5 MB.');await check();const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read the file'));reader.readAsDataURL(file)});const result=await api('/cv-import',{name:file.name,base64});update({masterCV:result.text,cvFilename:file.name});await save();setNotice('CV text extracted and saved. Review the text below before generating documents.')})}
 async function generate(job:Application){await run('Scoring compatibility and tailoring documents',async()=>{await check();await save();const result=await api('/application-draft',{title:job.title,company:job.company,description:job.description,profile:ref.current.profile+'\nVerified contact details: '+JSON.stringify(ref.current.contact),masterCV:ref.current.masterCV,provider:ref.current.provider,model:ref.current.model});await patch(job.id,{...result,status:'review',approvedAt:'',appliedAt:''});setConfirmed(false);setNotice('Drafts are ready. Check every personal claim, edit the documents, then approve.')})}
 async function download(job:Application,field:'resume'|'coverLetter',format:'docx'|'pdf'='docx'){await run('Downloading document',async()=>{await check();const result=await api('/application-document',{approved:['approved','applied'].includes(job.status),text:job[field],format,kind:field});const bytes=Uint8Array.from(atob(result.base64),(c)=>c.charCodeAt(0));const href=URL.createObjectURL(new Blob([bytes],{type:format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));const a=document.createElement('a');a.href=href;a.download=(job.company+'-'+job.title+'-'+field).replace(/[^a-z0-9-]/gi,'_').slice(0,100)+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000)})}
 const job=data.jobs.find(j=>j.id===selected);
 return <section className="applications">
  <div className="page-heading"><div><div className="eyebrow">JOB APPLICATIONS</div><h1>From opportunity to application.</h1><p>Match your experience, tailor your documents, and review before applying.</p></div><span>{dirty?'Changes not saved':'Saved'}</span></div>
  {!ready?<div className="panel" role="status">{!error&&<LoaderCircle className="spin" size={20}/>} {error?"Applications could not load":"Loading your saved applications..."}{error&&<button className="secondary" onClick={load}>Retry loading</button>}</div>:<>
  <div className="button-row"><button className={tab==='jobs'?'primary':'secondary'} onClick={()=>setTab('jobs')}>Jobs & applications ({data.jobs.length})</button><button className={tab==='profile'?'primary':'secondary'} onClick={()=>setTab('profile')}>Profile & master CV</button>{dirty&&<button className="secondary" disabled={!!busy} onClick={()=>run('Saving',()=>save())}>Save changes</button>}</div>
  {tab==='profile'?<div className="settings-grid application-panels"><section className="panel"><h2>Your profile</h2><p>Use your actual experience and preferences. These facts guide compatibility scoring and document customization.</p><fieldset disabled={!!busy}>
  {([['fullName','Full name'],['firstName','First name'],['lastName','Last name'],['email','Email'],['phone','Phone'],['linkedin','LinkedIn URL'],['portfolio','Portfolio URL']] as [keyof Contact,string][]).map(([key,label])=><label key={key}>{label}<input value={data.contact[key]} maxLength={500} onChange={e=>update({contact:{...data.contact,[key]:e.target.value}})}/></label>)}
  <label>Verified skills, experience and job preferences<textarea rows={8} maxLength={12000} value={data.profile} onChange={e=>update({profile:e.target.value})}/></label>
  <button className="primary" onClick={()=>run('Saving profile',async()=>{await save();setNotice('Profile saved.')})}>Save profile & CV</button></fieldset></section>
  <section className="panel"><h2>Master CV</h2><label>Upload PDF or DOCX<input type="file" accept=".pdf,.docx" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label><p>{data.cvFilename||'Upload a CV or paste its text below.'}</p><label>Extracted CV text<textarea rows={18} maxLength={50000} disabled={!!busy} value={data.masterCV} onChange={e=>update({masterCV:e.target.value})}/></label><small>The companion extracts text locally. This editable text is saved with your workspace; document layout is rebuilt for each application. Scanned PDFs require OCR.</small>
  <h2>Document generation</h2><label>AI provider<select disabled={!!busy} value={data.provider||'groq'} onChange={e=>{const provider=e.target.value as 'groq'|'ollama';setModels([]);setNotice('');setError('');update({provider,model:provider==='groq'?'openai/gpt-oss-20b':''})}}><option value="groq">Groq (hosted)</option><option value="ollama">Ollama (local)</option></select></label>
  <p>{data.provider==='groq'?'Groq uses the GROQ_API_KEY already configured in your companion. Your CV, profile and job description are sent to Groq when you generate documents. No local model or GPU is needed.':'Start Ollama and install a model on your computer, then check the connection.'}</p>
  <button className="secondary" disabled={!!busy} onClick={()=>run('Checking AI provider',async()=>{await check();const result=await api('/application-provider-status',{provider:data.provider});setModels(result.models);if(!data.model&&result.models.length){update({model:result.defaultModel||result.models[0]});await save()}setNotice(data.provider==='groq'?'Groq key is configured. Choose a model; generation will verify API access.':result.models.length?'Ollama connected. Choose the model to use.':'Ollama is running but no models are installed. Pull a model, then check again.')})}>{busy==='Checking AI provider'?<><LoaderCircle size={16} className="spin"/>Checking...</>:data.provider==='groq'?'Check Groq':'Check Ollama'}</button>
  <label>{data.provider==='groq'?'Groq model':'Installed model'}<select disabled={!!busy} value={data.model} onChange={e=>update({model:e.target.value})}><option value="">Choose a model</option>{[...new Set([data.model,...(data.provider==='groq'?['openai/gpt-oss-20b','openai/gpt-oss-120b']:models)])].filter(Boolean).map(model=><option key={model} value={model}>{data.provider==='groq'?model:model.endsWith("-gpu")?model+" (GPU)":model.endsWith("-cpu")?model+" (CPU)":model+" (automatic GPU/CPU)"}</option>)}</select></label></section></div>:<>
  <section className="panel application-panels"><h2>Find LinkedIn jobs</h2><p>Search using your profile and CV, then review and save listings. Sign in to LinkedIn in the companion Chrome window.</p><fieldset disabled={!!busy}><div className="settings-grid"><label>Search keywords<input maxLength={200} value={searchCriteria.keywords} placeholder="Leave blank to use your profile" onChange={e=>setSearchCriteria({...searchCriteria,keywords:e.target.value})}/></label><label>Search location<input maxLength={150} value={searchCriteria.location} placeholder="From your CV, or enter a location" onChange={e=>setSearchCriteria({...searchCriteria,location:e.target.value})}/></label><label>Work mode<select aria-label="Work mode" value={searchCriteria.workMode} onChange={e=>setSearchCriteria({...searchCriteria,workMode:e.target.value})}><option value="any">Any work mode</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select></label><label>Date posted<select aria-label="Date posted" value={searchCriteria.days} onChange={e=>setSearchCriteria({...searchCriteria,days:e.target.value})}><option value="any">Any time</option><option value="1">Past 24 hours</option><option value="7">Past week</option><option value="30">Past month</option></select></label><label>Listings to read<select aria-label="Listings to read" value={searchCriteria.limit} onChange={e=>setSearchCriteria({...searchCriteria,limit:Number(e.target.value)})}>{[3,5,10].map(n=><option key={n} value={n}>{n} jobs</option>)}</select></label></div><div className="button-row"><button className="secondary" onClick={()=>run('Suggesting search',async()=>{await check();const result=await api('/job-search-plan',{profile:ref.current.profile,masterCV:ref.current.masterCV});setSearchCriteria(current=>({...current,keywords:result.keywords,location:result.location}));setNotice('Search suggestions filled from your profile. Adjust them before searching.')})}>Use profile suggestions</button><button className="primary" onClick={()=>run('Searching LinkedIn jobs',async()=>{await check();setFoundJobs([]);setSearchSummary('');const result=await api('/job-search',{...searchCriteria,profile:ref.current.profile,masterCV:ref.current.masterCV,seenUrls:ref.current.jobs.map(job=>job.url)});setFoundJobs(result.jobs);setSearchSummary(result.keywords+(result.location?' ? '+result.location:''));setNotice(result.message)})}>{busy==='Searching LinkedIn jobs'?<><LoaderCircle size={16} className="spin"/>Searching...</>:'Search LinkedIn'}</button></div></fieldset>{searchSummary&&<p role="status">Results for {searchSummary}. This is a search match; score each saved job to assess compatibility.</p>}
  {foundJobs.length>0&&<><div className="button-row"><button className="secondary" disabled={!!busy||foundJobs.every(candidate=>data.jobs.some(job=>applicationJobKey(job.url)===applicationJobKey(candidate.url)))} onClick={()=>saveFound(foundJobs)}>Save all new jobs</button></div><div className="settings-grid">{foundJobs.map(candidate=>{const saved=data.jobs.some(job=>applicationJobKey(job.url)===applicationJobKey(candidate.url));return <article className="panel" key={candidate.url}><h3>{candidate.title}</h3><p>{[candidate.company,candidate.location].filter(Boolean).join(' ? ')}</p>{candidate.warning&&<p>{candidate.warning}</p>}{candidate.description&&<details><summary>Read job description</summary><p style={{whiteSpace:'pre-wrap'}}>{candidate.description}</p></details>}<div className="button-row"><a className="secondary" href={candidate.url} target="_blank" rel="noopener noreferrer">View LinkedIn job</a><button className="primary" disabled={!!busy||saved} onClick={()=>saveFound([candidate])}>{saved?'Saved':'Save job'}</button></div></article>})}</div></>}</section>
  <form className="panel application-panels" onSubmit={e=>{e.preventDefault();void run('Importing job',async()=>{await check();if(!validApplicationURL(url))throw Error('Enter a public HTTPS job link.');const result=await api('/job-import',{url});await add(result);setNotice('Job imported. Check the title, company and description before generating.')})}}><label>Job listing or application URL<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…" disabled={!!busy}/></label><div className="button-row"><button className="primary" disabled={!!busy}>{busy==='Importing job'?<><LoaderCircle size={16} className="spin"/>Importing...</>:'Import job link'}</button><button type="button" className="secondary" disabled={!!busy} onClick={()=>run('Adding job',()=>add({}))}>Add manually</button></div></form>
  <div className="application-layout"><aside className="panel"><label>Application status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All jobs</option>{['saved','review','approved','applied'].map(s=><option key={s}>{s}</option>)}</select></label>{data.jobs.filter(j=>filter==='all'||j.status===filter).map(j=><button key={j.id} className={'application-job '+(selected===j.id?'active':'')} disabled={!!busy} onClick={()=>{setSelected(j.id);setRetry(null)}}><strong>{j.title}</strong><span>{j.company||j.source}</span><small>{j.status}{j.score!==null?' · '+j.score+'% compatibility':''}</small></button>)}{!data.jobs.length&&<p>Import a job to start. Add your profile and master CV before generating.</p>}</aside>
  {job?<article className="panel"><div className="button-row"><button className="secondary" disabled={!!busy} onClick={()=>remove(job)}><Trash2 size={16}/>Remove job</button></div><fieldset disabled={!!busy||job.status==='applied'}><label>Job title<input value={job.title} onChange={e=>edit(job.id,{title:e.target.value})}/></label><label>Company<input value={job.company} onChange={e=>edit(job.id,{company:e.target.value})}/></label><label>Application URL<input type="url" value={job.url} onChange={e=>edit(job.id,{url:e.target.value})}/></label><label>Job description<textarea rows={8} maxLength={30000} value={job.description} onChange={e=>edit(job.id,{description:e.target.value,score:null})}/></label><button className="primary" disabled={!job.description.trim()||!data.masterCV.trim()||!data.profile.trim()||!data.model} onClick={()=>generate(job)}>{busy.startsWith('Scoring')?<><LoaderCircle size={16} className="spin"/>Generating documents...</>:job.resume?'Regenerate documents':'Score & tailor documents'}</button>{(!data.masterCV||!data.profile||!data.model)&&<p>Complete Profile & master CV and choose an AI model first.</p>}</fieldset>
  {job.score!==null&&<section className="application-match"><h2>{job.score}% compatibility</h2><p>{job.summary}</p><small>AI estimate based on your supplied facts, not a hiring probability.</small><div className="settings-grid"><div><h3>Matches</h3><ul>{job.matches.map((text,i)=><li key={i}>{text}</li>)}</ul></div><div><h3>Gaps & questions</h3><ul>{job.gaps.map((text,i)=><li key={i}>{text}</li>)}</ul></div></div></section>}
  {job.resume&&<><details><summary>Check source evidence</summary>{job.evidence.map((e,i)=><p key={i}><strong>{e.claim}</strong><br/><q>{e.source}</q></p>)}</details><label>Tailored resume<textarea aria-label="Tailored resume" rows={18} value={job.resume} disabled={!!busy||job.status==='applied'} onChange={e=>edit(job.id,{resume:e.target.value})}/></label><label>Cover letter<textarea aria-label="Cover letter" rows={12} value={job.coverLetter} disabled={!!busy||job.status==='applied'} onChange={e=>edit(job.id,{coverLetter:e.target.value})}/></label>
  {job.status==='review'&&<><label className="application-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the documents and verified all personal claims.</label><button className="primary" disabled={!!busy||!confirmed||!job.resume.trim()||!job.coverLetter.trim()} onClick={()=>run('Approving documents',async()=>{await patch(job.id,{status:'approved',approvedAt:new Date().toISOString()});setNotice('Approved. Download the documents or prepare the application form.')})}>Approve documents</button></>}
  {['approved','applied'].includes(job.status)&&<><div className="button-row"><button className="secondary" disabled={!!busy} onClick={()=>download(job,'resume')}>Download resume DOCX</button><button className="secondary" disabled={!!busy} onClick={()=>download(job,'resume','pdf')}>Download resume PDF</button><button className="secondary" disabled={!!busy} onClick={()=>download(job,'coverLetter')}>Download cover letter DOCX</button>{job.status==='approved'&&<button className="primary" disabled={!!busy||!validApplicationURL(job.url)||dirty} onClick={()=>run('Preparing application',async()=>{await check();const result=await api('/application-prepare',{approved:true,url:job.url,resume:job.resume,coverLetter:job.coverLetter,contact:data.contact});setNotice(result.message+(result.filled?.length?' Filled: '+result.filled.join(', ')+'.':'')+(result.skipped?.length?' Review manually: '+result.skipped.join(', ')+'.':''))})}>{busy==='Preparing application'?<><LoaderCircle size={16} className="spin"/>Preparing...</>:'Prepare application'}</button>}</div><p>Resume downloads use a single-column layout with readable text and standard section headings. PDF contains selectable text. Follow the employer?s requested file format.</p><p>Standard Lever and Greenhouse forms support contact fields and DOCX attachments. Other sites open for manual application. Screening answers and final submission remain yours.</p>{job.status==='approved'?<><label className="application-confirm"><input type="checkbox" checked={submitted} onChange={e=>setSubmitted(e.target.checked)}/>I submitted this application on the employer’s website.</label><button className="secondary" disabled={!!busy||!submitted} onClick={()=>run('Recording application',()=>patch(job.id,{status:'applied',appliedAt:new Date().toISOString()}))}>Mark as applied</button></>:<p>Recorded as applied: {new Date(job.appliedAt).toLocaleDateString()}</p>}</>}
  </>}
  </article>:<div className="empty-state"><h2>Select a job to build your application.</h2><p>Your master CV stays the starting point. Each job gets its own reviewed documents.</p></div>}</div></>}
  </>}
 {(busy||error||notice)&&<div className={'application-feedback '+(busy?'is-working':error?'is-error':'is-success')} role={error?'alert':'status'} aria-live={error?'assertive':'polite'}>
 {busy?<LoaderCircle className="spin" size={22}/>:error?<AlertCircle size={22}/>:<CheckCircle2 size={22}/>}
 <div><strong>{busy?stage:error?'Action could not finish':'Done'}</strong><p>{busy?(busy.startsWith('Scoring')?(data.provider==='groq'?'Groq is generating your documents online. Keep this page open.':'Your local model is working. CPU generation can take several minutes. Keep this page open.'):'Please wait. Keep this page open until the action finishes.'):error||notice}</p>{busy&&<><span className="elapsed" aria-live="off">Elapsed: {Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span><progress aria-label={stage}/></>}</div>
 {!busy&&<div className="button-row">{error&&retry&&<button className="secondary" onClick={()=>retry()}>Retry action</button>}<button className="text-button" aria-label="Dismiss notification" onClick={()=>{setError('');setNotice('');setRetry(null)}}><X size={18}/></button></div>}
 </div>}
 </section>;
}
